FROM ubuntu
RUN apt-get update; \
    apt-get install -y --no-install-recommends ca-certificates wget unzip; \
    rm -rf /var/lib/apt/lists/*
COPY /etc/gai.conf /etc/gai.conf
COPY sh /root/cmd.sh
CMD exec /bin/sh /root/cmd.sh
