name: build-docker

on:
  workflow_dispatch:
  push:
    branches:
      - HEAD
    paths:
      - '.github/workflows/docker.yml'
      - 'sh'
    
concurrency:
  group: build-docker
  cancel-in-progress: true
    
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - run: |
          cat > Dockerfile <<EOF
          FROM alpine
          COPY sh /root/cmd.sh
          CMD exec /bin/sh /root/cmd.sh
          EOF
      
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/2048:latest
